### ISSUE TITLE
Updating to v2.0.0 breaks building of a create-react-app application

### ISSUE THREAD

**Issue by koox00** [yahoo/subscribe-ui-event#53] opened 2018-06-04 17:35 UTC
Updating to `v2.0.0` breaks the production build of an app created with `create-react-app`.

```
Failed to minify the code from this file:

        ./node_modules/subscribe-ui-event/dist-es/lib/listen.js:28

Read more here: http://bit.ly/2tRViJ9
```

**Comment by redonkulus** [comment] 2018-06-04 17:42
Related issue https://github.com/yahoo/react-stickynode/issues/111

**Comment by houkanshan** [comment] 2018-06-06 08:00
Hi, I just updated to 2.0.2 but still caught the error of using `const` in IE 10, Chrome < 41 and Safari 9

I believe these 2 files `index.es.js` and `index.js` should also be transpiled with Babel?

**Comment by redonkulus** [comment] 2018-06-06 17:18
The `index.es.js` file should only be used by browsers that support ES6 features. Older browsers should use `index.js`. Compiling `index.es.js` to ES5 defeats the purpose of the file itself. How is the `index.es.js` file being loaded in older browsers? What is your compile step like?

**Comment by houkanshan** [comment] 2018-06-07 04:06
Thanks for response. I created a demo to show it: https://gist.github.com/houkanshan/8b2734c61b4b1ef7055a951a082db020


1. In my config for babel-loader, `node_modules & bower_components` is excluded for improving performance according to the [doc](https://webpack.js.org/loaders/babel-loader/#babel-loader-is-slow-).
2. webpack choose to import `index.es.js` by `pkg.module`

According to the [rollup's doc](http://2ality.com/2017/06/pkg-esnext.html#comment-3338827567) and the [discussion on webpack](https://github.com/webpack/webpack/issues/1979#issuecomment-339738809), I believe currently the `pkg.module` is only for ES2015 module syntax, the rest of the code should still be precompiled to ES5. As for pure ES6 code, maybe we can use other name like `pkg.esnext` in the future according to [2ality's proposal](http://2ality.com/2017/06/pkg-esnext.html#comment-3338827567)?

**Comment by azu** [comment] 2018-06-28 08:06
webpack use `"module"` field by default.
Because, default [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields)'s value is `['browser', 'module', 'main']`.

(I've used [react-stickynode](https://github.com/yahoo/react-stickynode). it break old browser for the above reason) 

Currently, I've used a workaround for this issue.

`webpack.config.js`:

```js
module.exports = {
    // ...cut...
    alias: {
        'subscribe-ui-event': path.join(__dirname, `node_modules/subscribe-ui-event/index.js`)
    )
  }
}
```

**Comment by houkanshan** [comment] 2018-06-28 08:44
@azu , yes, Webpack use "module" field by default because they are following the Rollup's proposal about `pkg.module`. 

But I had checked `node_modules/subscribe-ui-event/index.js` and it's sill using the `const` keyword. So I'm not sure how this alias fixed that problem.

Anyway, this is my workaround:

```js
{
  loader: 'babel-loader',
  test: /\.jsx?$/,
  exclude: {
    test: [
      path.resolve(__dirname, '../node_modules'),
      path.resolve(__dirname, '../bower_components'),
    ],
    exclude: /subscribe-ui-event/,
  },
},
```

It informs the developers that "`subscribe-ui-event` has ES6 code, Babel should handle it".

**Comment by stefensuhat** [comment] 2018-07-13 13:21
is this fixed?. It happen on my project too. Can't build the project.

**Comment by kelly-tock** [comment] 2018-07-19 17:20
I had to downgrade react-stickynode because of this.

**Comment by kelly-tock** [comment] 2018-07-19 17:21
what about adding a browser field with no `const` in it?

**Comment by kelly-tock** [comment] 2018-07-19 17:30
@houkanshan tried code above, did not change that const was still in the file.

**Comment by redonkulus** [comment] 2018-07-19 22:04
@roderickhsiao can this be closed now? or we still have an issue?

**Comment by roderickhsiao** [comment] 2018-07-19 22:51
It seems like the build error is gone, now the issue is the `const` part for old browser.

I think we could just replace `const` from https://github.com/yahoo/subscribe-ui-event/blob/master/index.js

**Comment by kelly-tock** [comment] 2018-07-20 00:30
Yes please

**Comment by roderickhsiao** [comment] 2018-07-26 07:36
@redonkulus could close this :)

**Closed** 2018-07-26 10:41 UTC
